version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app
        container_name: project_test_nginx

    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: project_test_app

#    db:
#        image: mysql:8.0
#        restart: always
#        volumes:
#            - ./tmp/db:/var/lib/mysql
#        environment:
#            MYSQL_DATABASE: test
#            MYSQL_ROOT_PASSWORD: root
#        ports:
#            - 8101:3306
#        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
#        container_name: project_test_db

    db:
        image: postgres
        restart: always
        container_name: postgres
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgAdmin
        ports:
            - "5050:80"
        depends_on:
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: numbovskij@gmail.com
            PGADMIN_DEFAULT_PASSWORD: password
